/* SECUREYE — Store data (source: Precios + Catálogo commercial tables)
   Each item: id, cat, name, spec, price (COP, base), priceMax, eta, deliverable.
   Prices are reference ranges; cart uses price (base). Keep in sync with catalogo.html/pricing.html */
window.SECUREYE_CATALOG = [
  // Cámaras — 15 refs
  {id:"CAM-001",cat:"camaras",name:"Cámara IP 2 MP",spec:"1080p · IR · PoE · exterior — Aluminio/ABS, CMOS, lente, IR, RJ45",price:180000,priceMax:300000,eta:"1–5 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-002",cat:"camaras",name:"Cámara IP 4 MP",spec:"2K · IR/LED · PoE — Aluminio, CMOS 4 MP, lente 2.8 mm",price:280000,priceMax:450000,eta:"1–7 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-003",cat:"camaras",name:"Cámara IP 5 MP",spec:"Alta resolución · IR · PoE — Metal/ABS, CMOS, óptica, LEDs IR",price:350000,priceMax:550000,eta:"2–7 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-004",cat:"camaras",name:"Cámara IP 8 MP",spec:"4K · H.265+ · PoE — Aluminio, CMOS, lente, procesador",price:500000,priceMax:900000,eta:"3–10 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-005",cat:"camaras",name:"Domo IP 2 MP",spec:"Interior/exterior · IR — Metal/ABS, domo policarbonato",price:180000,priceMax:320000,eta:"1–5 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-006",cat:"camaras",name:"Domo IP 4 MP",spec:"IP67 · IR — Aluminio, policarbonato, CMOS",price:280000,priceMax:450000,eta:"1–7 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-007",cat:"camaras",name:"Bala IP 4 MP",spec:"IR/LED · IP67 — Cuerpo metálico, CMOS, lente",price:300000,priceMax:500000,eta:"1–7 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-008",cat:"camaras",name:"Bala IP 8 MP",spec:"4K · IR · PoE — Aluminio, CMOS, óptica",price:500000,priceMax:900000,eta:"3–10 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-009",cat:"camaras",name:"Wi-Fi 2/3 MP",spec:"App móvil · audio — ABS, CMOS, Wi-Fi, micrófono",price:150000,priceMax:280000,eta:"1–5 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-010",cat:"camaras",name:"ColorVu / Full Color",spec:"Color en baja iluminación — sensor alta sensibilidad, LED",price:400000,priceMax:800000,eta:"3–10 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-011",cat:"camaras",name:"Cámara IA",spec:"Personas/vehículos — CMOS, procesador IA, IR/LED",price:500000,priceMax:1200000,eta:"3–15 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-012",cat:"camaras",name:"PTZ zoom 360°",spec:"Zoom óptico · giro 360° — Metal, motores, zoom, CMOS",price:1000000,priceMax:4000000,eta:"5–20 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-013",cat:"camaras",name:"PTZ profesional 25x/30x/40x",spec:"Metal, motor, óptica profesional",price:3000000,priceMax:10000000,eta:"10–30 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-014",cat:"camaras",name:"Cámara panorámica 180/360°",spec:"Multisensor · óptica gran angular",price:1500000,priceMax:5000000,eta:"7–20 días",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"CAM-015",cat:"camaras",name:"Cámara térmica",spec:"Detección térmica — sensor térmico, óptica, procesador",price:4000000,priceMax:null,eta:"Bajo pedido",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  // DVR / NVR — 10 refs
  {id:"REC-001",cat:"grabadores",name:"DVR 4 canales",spec:"1080p · H.265",price:250000,priceMax:400000,eta:"1–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-002",cat:"grabadores",name:"DVR 8 canales",spec:"1080p/5MP",price:350000,priceMax:550000,eta:"1–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-003",cat:"grabadores",name:"DVR 16 canales",spec:"5MP · H.265+",price:450000,priceMax:700000,eta:"1–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-004",cat:"grabadores",name:"DVR 32 canales",spec:"5MP/4K según modelo",price:800000,priceMax:1500000,eta:"3–10 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-005",cat:"grabadores",name:"NVR 4 canales",spec:"IP · H.265+",price:300000,priceMax:500000,eta:"1–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-006",cat:"grabadores",name:"NVR 8 canales",spec:"IP · PoE",price:450000,priceMax:750000,eta:"1–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-007",cat:"grabadores",name:"NVR 16 canales",spec:"IP · PoE · 4K",price:700000,priceMax:1400000,eta:"2–10 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-008",cat:"grabadores",name:"NVR 32 canales",spec:"IP · 4K",price:1200000,priceMax:2500000,eta:"3–15 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-009",cat:"grabadores",name:"NVR empresarial 64+ canales",spec:"64+ canales — bajo pedido",price:2500000,priceMax:null,eta:"Bajo pedido",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"REC-010",cat:"grabadores",name:"NVR IA analítica avanzada",spec:"Analítica con IA",price:2000000,priceMax:null,eta:"7–20 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // Discos — 6 refs (HDD vigilancia)
  {id:"HDD-001",cat:"almacenamiento",name:"HDD vigilancia 1 TB",spec:"2–4 cámaras · operación continua",price:250000,priceMax:350000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"HDD-002",cat:"almacenamiento",name:"HDD vigilancia 2 TB",spec:"4–8 cámaras · operación continua",price:350000,priceMax:500000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"HDD-003",cat:"almacenamiento",name:"HDD vigilancia 4 TB",spec:"8–16 cámaras",price:500000,priceMax:750000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"HDD-004",cat:"almacenamiento",name:"HDD vigilancia 6 TB",spec:"16+ cámaras",price:700000,priceMax:1000000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"HDD-005",cat:"almacenamiento",name:"HDD vigilancia 8 TB",spec:"Sistemas profesionales",price:900000,priceMax:1300000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"HDD-006",cat:"almacenamiento",name:"HDD vigilancia 12 TB",spec:"Grandes instalaciones",price:1300000,priceMax:null,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // PoE / redes — 9 refs
  {id:"NET-001",cat:"redes",name:"Switch PoE 4 puertos",spec:"PoE 802.3af",price:180000,priceMax:300000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-002",cat:"redes",name:"Switch PoE 8 puertos",spec:"PoE",price:250000,priceMax:500000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-003",cat:"redes",name:"Switch PoE 16 puertos",spec:"PoE",price:500000,priceMax:900000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-004",cat:"redes",name:"Switch PoE 24 puertos",spec:"PoE",price:800000,priceMax:1500000,eta:"2–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-005",cat:"redes",name:"Switch administrable",spec:"Gestionable",price:700000,priceMax:null,eta:"2–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-006",cat:"redes",name:"Switch industrial PoE",spec:"Industrial",price:1000000,priceMax:null,eta:"3–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-007",cat:"redes",name:"Router empresarial",spec:"Alta capacidad",price:300000,priceMax:1500000,eta:"1–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-008",cat:"redes",name:"Access Point",spec:"Wi-Fi empresarial",price:250000,priceMax:800000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"NET-009",cat:"redes",name:"Enlace inalámbrico",spec:"Punto a punto",price:500000,priceMax:2000000,eta:"2–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // Cableado — 10 refs
  {id:"CAB-001",cat:"cableado",name:"UTP Cat5e · caja 305 m",spec:"Cable UTP",price:350000,priceMax:600000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-002",cat:"cableado",name:"UTP Cat6 · caja 305 m",spec:"Cable UTP",price:500000,priceMax:900000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-003",cat:"cableado",name:"Cable coaxial CCTV · metro",spec:"Coaxial",price:1500,priceMax:3500,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-004",cat:"cableado",name:"Balun HD · par",spec:"Transceptor",price:20000,priceMax:60000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-005",cat:"cableado",name:"Conector BNC · unidad",spec:"BNC",price:2000,priceMax:8000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-006",cat:"cableado",name:"Jack DC · unidad",spec:"Alimentación",price:2000,priceMax:6000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-007",cat:"cableado",name:"Patch cord 1–3 m",spec:"UTP",price:8000,priceMax:25000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-008",cat:"cableado",name:"Patch panel Cat6 · 24 puertos",spec:"Rack",price:150000,priceMax:350000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-009",cat:"cableado",name:"Caja exterior ABS/metal",spec:"Protección",price:20000,priceMax:70000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"CAB-010",cat:"cableado",name:"Canaleta · metro",spec:"PVC",price:5000,priceMax:25000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // UPS — 7 refs
  {id:"PWR-001",cat:"energia",name:"UPS 600 VA",spec:"Autonomía corta",price:180000,priceMax:300000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-002",cat:"energia",name:"UPS 1000 VA",spec:"Hogar/comercio",price:300000,priceMax:500000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-003",cat:"energia",name:"UPS 1500 VA",spec:"Pequeña empresa",price:500000,priceMax:800000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-004",cat:"energia",name:"UPS 2200 VA",spec:"Empresa",price:800000,priceMax:1500000,eta:"1–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-005",cat:"energia",name:"Regulador de voltaje",spec:"Protección",price:100000,priceMax:300000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-006",cat:"energia",name:"Protector eléctrico",spec:"Supresor",price:50000,priceMax:150000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PWR-007",cat:"energia",name:"Fuente CCTV 12 V",spec:"Alimentación cámaras",price:30000,priceMax:150000,eta:"1–3 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // Monitoreo — 7 refs
  {id:"MON-001",cat:"monitoreo",name:"Monitor 22\"",spec:"Full HD",price:350000,priceMax:600000,eta:"1–5 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-002",cat:"monitoreo",name:"Monitor 24\"",spec:"Full HD",price:450000,priceMax:750000,eta:"1–5 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-003",cat:"monitoreo",name:"Monitor 27\"",spec:"Full HD/2K",price:600000,priceMax:1000000,eta:"1–5 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-004",cat:"monitoreo",name:"Monitor 32\"",spec:"Full HD/4K",price:800000,priceMax:1500000,eta:"1–5 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-005",cat:"monitoreo",name:"TV 43\"",spec:"Smart TV",price:1000000,priceMax:1800000,eta:"1–7 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-006",cat:"monitoreo",name:"TV 55\"",spec:"4K Smart",price:1500000,priceMax:2500000,eta:"1–7 días",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  {id:"MON-007",cat:"monitoreo",name:"Video wall",spec:"Bajo cotización",price:null,priceMax:null,eta:"Cotización",img:"assets/img/team-1.jpg",imgWebp:"assets/img/team-1.webp"},
  // Control de acceso — 9 refs
  {id:"ACC-001",cat:"acceso",name:"Lector RFID",spec:"Lector + tarjetas",price:150000,priceMax:350000,eta:"1–5 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-002",cat:"acceso",name:"Huella digital",spec:"Lector biométrico",price:300000,priceMax:700000,eta:"1–7 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-003",cat:"acceso",name:"Reconocimiento facial",spec:"Cámara + terminal",price:600000,priceMax:2000000,eta:"2–10 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-004",cat:"acceso",name:"Controladora 1–4 puertas",spec:"Panel de acceso",price:400000,priceMax:1500000,eta:"2–10 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-005",cat:"acceso",name:"Cerradura magnética 280–600 kg",spec:"Electroimán",price:150000,priceMax:400000,eta:"1–5 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-006",cat:"acceso",name:"Botón de salida",spec:"Metálico/ABS",price:30000,priceMax:100000,eta:"1–3 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-007",cat:"acceso",name:"Tarjeta RFID PVC",spec:"Tarjeta / llavero",price:3000,priceMax:10000,eta:"1–3 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-008",cat:"acceso",name:"Lector vehicular largo alcance",spec:"RFID vehículo",price:1000000,priceMax:null,eta:"5–10 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  {id:"ACC-009",cat:"acceso",name:"Torniquete acero inoxidable",spec:"Control peatonal",price:4000000,priceMax:null,eta:"10–20 días",img:"assets/img/team-2.jpg",imgWebp:"assets/img/team-2.webp"},
  // Alarmas — 8 refs
  {id:"ALM-001",cat:"alarmas",name:"Panel de alarma",spec:"Central cableada/inalámbrica",price:250000,priceMax:700000,eta:"1–5 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-002",cat:"alarmas",name:"Sensor PIR",spec:"Infrarrojo pasivo",price:50000,priceMax:150000,eta:"1–3 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-003",cat:"alarmas",name:"Sensor magnético",spec:"Puerta/ventana",price:20000,priceMax:60000,eta:"1–3 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-004",cat:"alarmas",name:"Sirena interior",spec:"110 dB",price:40000,priceMax:100000,eta:"1–3 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-005",cat:"alarmas",name:"Sirena exterior",spec:"Con flash",price:80000,priceMax:200000,eta:"1–3 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-006",cat:"alarmas",name:"Teclado alarma",spec:"LCD / numérico",price:100000,priceMax:300000,eta:"1–5 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-007",cat:"alarmas",name:"Comunicador GSM/4G",spec:"Reporte a central",price:250000,priceMax:600000,eta:"1–5 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  {id:"ALM-008",cat:"alarmas",name:"Botón de pánico",spec:"Inalámbrico",price:50000,priceMax:150000,eta:"1–3 días",img:"assets/img/team-3.jpg",imgWebp:"assets/img/team-3.webp"},
  // Videoporteros — 6 refs
  {id:"VIP-001",cat:"videoporteros",name:"Videoportero básico",spec:"Audio/video · 1 vivienda",price:250000,priceMax:500000,eta:"1–5 días",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  {id:"VIP-002",cat:"videoporteros",name:"Videoportero IP",spec:"Red IP · app móvil",price:500000,priceMax:1200000,eta:"2–7 días",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  {id:"VIP-003",cat:"videoporteros",name:"Videoportero Wi-Fi",spec:"Inalámbrico",price:400000,priceMax:900000,eta:"1–5 días",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  {id:"VIP-004",cat:"videoporteros",name:"Monitor interior videoportero",spec:"Pantalla 7\"",price:300000,priceMax:800000,eta:"1–5 días",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  {id:"VIP-005",cat:"videoporteros",name:"Kit videoportero residencial",spec:"Frente + monitor + fuente",price:500000,priceMax:1500000,eta:"1–7 días",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  {id:"VIP-006",cat:"videoporteros",name:"Kit videoportero edificio",spec:"Multivivienda — cotización",price:null,priceMax:null,eta:"Cotización",img:"assets/img/team-4.jpg",imgWebp:"assets/img/team-4.webp"},
  // Perimetral — 6 refs
  {id:"PER-001",cat:"perimetral",name:"Energizador cerca eléctrica",spec:"Cercado eléctrico",price:400000,priceMax:1200000,eta:"1–5 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PER-002",cat:"perimetral",name:"Kit cerca eléctrica",spec:"Postes, alambre, energizador",price:800000,priceMax:2000000,eta:"2–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PER-003",cat:"perimetral",name:"Sensor perimetral",spec:"Detección exterior",price:300000,priceMax:null,eta:"2–7 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PER-004",cat:"perimetral",name:"Barrera vehicular",spec:"Brazo automático",price:3000000,priceMax:7000000,eta:"7–15 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PER-005",cat:"perimetral",name:"Control vehicular",spec:"Antena + tags",price:1000000,priceMax:null,eta:"5–10 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"PER-006",cat:"perimetral",name:"Automatización portón",spec:"Motor + cremallera",price:1500000,priceMax:4000000,eta:"3–10 días",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  // Paquetes — 4 refs (pricing.html parity)
  {id:"PKG-001",cat:"paquetes",name:"Hogar Básico · 4 cámaras",spec:"4× 2MP + DVR 4ch · HDD 1TB + cableado + app móvil — instalación básica incluida",price:1200000,priceMax:1800000,eta:"1–5 días",badge:"Hogar",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"PKG-002",cat:"paquetes",name:"Comercio · 8 cámaras",spec:"8× 2–4MP + DVR/XVR 8/16ch · HDD 2TB — remoto + instalación",price:2500000,priceMax:4000000,eta:"1–7 días",badge:"Más vendido",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"PKG-003",cat:"paquetes",name:"Empresarial IP · 8 cámaras",spec:"8× IP 4MP + NVR 16ch PoE · HDD 4TB + rack/Cat6/UPS — instalación incluida",price:6000000,priceMax:10000000,eta:"2–10 días",badge:"Empresarial",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  {id:"PKG-004",cat:"paquetes",name:"Industrial · 16–32 cámaras",spec:"IP 4/8MP + PTZ + analítica + NVR empresarial + red estructurada + monitoreo",price:15000000,priceMax:null,eta:"10–30 días",badge:"Industrial",img:"assets/img/camera-closeup.jpg",imgWebp:"assets/img/camera-closeup.webp"},
  // Mantenimiento mensual — 3 planes
  {id:"MNT-001",cat:"mantenimiento",name:"Mantenimiento Básico",spec:"Revisión remota · diagnóstico · soporte telefónico · revisión grabación",price:150000,priceMax:300000,eta:"Mensual",badge:"/mes",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"MNT-002",cat:"mantenimiento",name:"Mantenimiento Profesional",spec:"Visita periódica · limpieza · cámaras/NVR/DVR · almacenamiento · remoto",price:300000,priceMax:600000,eta:"Mensual",badge:"/mes",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"},
  {id:"MNT-003",cat:"mantenimiento",name:"Mantenimiento Empresarial",spec:"Preventivo · soporte prioritario · red/UPS/acceso · informes · monitoreo",price:600000,priceMax:1500000,eta:"Mensual",badge:"/mes",img:"assets/img/installer.jpg",imgWebp:"assets/img/installer.webp"}
];
window.SECUREYE_CATS = [
  {id:"all",label:"Todo"},
  {id:"paquetes",label:"Paquetes"},
  {id:"camaras",label:"Cámaras"},
  {id:"grabadores",label:"DVR/NVR"},
  {id:"almacenamiento",label:"Discos"},
  {id:"redes",label:"PoE / Redes"},
  {id:"cableado",label:"Cableado"},
  {id:"energia",label:"UPS"},
  {id:"monitoreo",label:"Monitores"},
  {id:"acceso",label:"Acceso"},
  {id:"alarmas",label:"Alarmas"},
  {id:"videoporteros",label:"Videoporteros"},
  {id:"perimetral",label:"Perimetral"},
  {id:"mantenimiento",label:"Mantenimiento"}
];
